name: Setup Chaskiq

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git postgresql redis-server imagemagick

    - name: Configure PostgreSQL
      run: |
        sudo service postgresql start
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

    - name: Set up PostgreSQL
      env:
        PGPASSWORD: postgres
      run: |
        psql -U postgres -c "CREATE USER chaskiq WITH PASSWORD 'password';"
        psql -U postgres -c "ALTER USER chaskiq WITH SUPERUSER;"
        psql -U postgres -c "CREATE DATABASE chaskiq_development OWNER chaskiq;"

    - name: Install Bundler
      run: gem install bundler

    - name: Install gems
      run: bundle install

    - name: Set up Chaskiq
      run: |
        cp .env.example .env
        sed -i 's/ADMIN_EMAIL=.*/ADMIN_EMAIL=your@email.com/' .env
        sed -i 's/ADMIN_PASSWORD=.*/ADMIN_PASSWORD=123456/' .env
        bundle exec rails db:setup

    - name: Run tests
      run: bundle exec rspec
